on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "Job 1 is executed successfully"

  job2:
    runs-on: ubuntu-latest
    needs: job1 #for dependent jobs
    steps:
      - name: Job 2
        run: echo "Job 2 executed successfully"
